# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Circumventing Censorship
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "/circumventing-censorship" # the subpath of your site, e.g. /blog
baseurl: "/circumvention" # the subpath of your site, e.g. /blog
#baseurl: "/circumventing-censorship" # the subpath of your site, e.g. /blog
#url: "https://projects.voanews.com/circumventing-censorship" # http://projects.voanews.com/circumvention #localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

canonical_url_base: "https://projects.voanews.com/circumvention"

twitter_username: "@BrianWmson"

language_number: 3 # is this currently being used?

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:categories/:title

# If you want include the .html in the url
# Or exclue it and fix it with .htaccess
#permalink: /:categories/:title.html
